### ISSUE TITLE
Update github actions for deprecated node 12

### ISSUE THREAD

**Issue by dmijatovic** [research-software-directory/RSD-as-a-service#618]
The last release action produces number of warnings to be addressed.

See notification https://github.com/research-software-directory/RSD-as-a-service/actions/runs/3345281898

After initial investigation I conclude:

*  TriPSs/conventional-changelog-action@v3 is just updated by owner - **no action required**
* `set-output` should be updated **before** 01-06-2023, [see info here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

```yaml
# derecated
- name: Set output
  run: echo "::set-output name={name}::{value}"

# use this instead
- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```
After initial tests it seems that `TriPSs/conventional-changelog-action@v3` depends on `@actions/core` that also need to update, [see issue](https://github.com/TriPSs/conventional-changelog-action/issues/182)

## Next step
Test these adjustments on the fork and monitor status of [@actions/core](https://github.com/actions/toolkit/tree/main/packages/core)
